FROM paddledev/paddle:gpu-devel-latest
MAINTAINER Paddle Paddle Dev Team <paddle-dev@baidu.com>
ENV PADDLE_SOURCE_ROOT /paddle
ENV OUTPUT_DIR /output
ENV PADDLE_WITH_GPU OFF
COPY builder.sh /etc/profile.d/
